const ch_list = [
	{"chnum":15, "chname":"スピードチャンネル1", chelement:{option:["single","set"]},price:{single:900, set:1200}},
	{"chnum":16, "chname":"スピードチャンネル2", chelement:{option:["set"]},price:{set:0}}, //スピード1.2セットだと1200
	{"chnum":21, "chname":"アニマックスSD", chelement:{},price:{}},
	{"chnum":22, "chname":"えひめ・すこやかチャンネル", chelement:{},price:{}},
	{"chnum":23, "chname":"えひめ・まなビジョン", chelement:{},price:{}},
	{"chnum":100, "chname":"プレビュー", chelement:{},price:{}},
	{"chnum":105, "chname":"ダンスチャンネル", chelement:{ent:[]},price:{}},
	{"chnum":113, "chname":"Eおんがくチャンネル", chelement:{},price:{}},
	{"chnum":114, "chname":"愛顔スポーツチャンネル", chelement:{},price:{}},
	{"chnum":115, "chname":"ワンダーチャンネル", chelement:{},price:{}},
	{"chnum":116, "chname":"マチスキチャンネル", chelement:{},price:{}},
	{"chnum":117, "chname":"マツリ☆チャンネル", chelement:{},price:{}},
	{"chnum":118, "chname":"NHKワールドJAPAN", chelement:{},price:{}},
	{"chnum":119, "chname":"ウィットチャンネル", chelement:{},price:{}},
	{"chnum":120, "chname":"鉄道チャンネル", chelement:{osu:[]},price:{}},
	{"chnum":121, "chname":"ディスカバリーチャンネル", chelement:{osu:[]},price:{}},
	{"chnum":122, "chname":"ムービープラスHD", chelement:{osu:[]},price:{}},
	{"chnum":123, "chname":"LaLaTV(HD)", chelement:{osu:[]},price:{}},
	{"chnum":124, "chname":"スーパー! ドラマTV HD", chelement:{osu:[]},price:{}},
	{"chnum":125, "chname":"日本映画専門チャンネルHD", chelement:{option:[], osu:[]},price:700},
	{"chnum":126, "chname":"アジアドラマチックＴＶ★HD", chelement:{option:[], osu:[]},price:600},
	{"chnum":127, "chname":"衛星劇場HD", chelement:{option:[]},price:1800},
	{"chnum":129, "chname":"ディズニーXD HD", chelement:{},price:{}},
	{"chnum":131, "chname":"FOX HD", chelement:{ent:[], ote:[]},price:{}},
	{"chnum":132, "chname":"J SPORTS 4 HD", chelement:{option:[]},price:1300},
	{"chnum":134, "chname":"ヒストリーチャンネルHD", chelement:{osu:[]},price:{}},
	{"chnum":135, "chname":"チャンネル銀河", chelement:{osu:[]},price:{}},
	{"chnum":136, "chname":"テレ朝チャンネル1", chelement:{option:[], dor:[]},price:600},
	{"chnum":137, "chname":"フジテレビNEXT", chelement:{option:[]},price:1000},
	{"chnum":138, "chname":"フジテレビONE", chelement:{sup:[]},price:{}},
	{"chnum":139, "chname":"フジテレビTWO", chelement:{sup:[]},price:{}},
	{"chnum":140, "chname":"ショップチャンネル", chelement:{},price:{}},
	{"chnum":141, "chname":"ホームドラマチャンネルHD", chelement:{option:[], dor:[]},price:600},
	{"chnum":142, "chname":"ナショナル ジオグラフィック", chelement:{ent:[], ote:[]},price:{}},
	{"chnum":143, "chname":"旅チャンネルHD", chelement:{osu:[]},price:{}},
	{"chnum":144, "chname":"TBSチャンネル1", chelement:{option:[], sup:[]},price:600},
	{"chnum":145, "chname":"釣りビジョンHD", chelement:{option:[], osu:[]},price:1200},
	{"chnum":146, "chname":"GAORA SPORTS HD", chelement:{osu:[]},price:{}},
	{"chnum":147, "chname":"スカイA", chelement:{option:[], sup:[], ote:[]},price:1000},
	{"chnum":148, "chname":"AXN HD", chelement:{osu:[]},price:{}},
	{"chnum":149, "chname":"アニマックスHD", chelement:{osu:[]},price:{}},
	{"chnum":150, "chname":"MTV", chelement:{dor:[], ote:[]},price:{}},
	{"chnum":151, "chname":"チャンネルNECO-HD", chelement:{osu:[]},price:{}},
	{"chnum":152, "chname":"TBS NEWS", chelement:{option:[], osu:[]},price:372},
	{"chnum":153, "chname":"AXNミステリーHD", chelement:{osu:[]},price:{}},
	{"chnum":154, "chname":"タカラヅカ", chelement:{},price:{}},
	{"chnum":155, "chname":"WOWOWプラス", chelement:{option:[],dor:[], ote:[]},price:700},
	{"chnum":156, "chname":"スペースシャワーTV HD", chelement:{osu:[]},price:{}},
	{"chnum":157, "chname":"ファミリー劇場HD", chelement:{osu:[]},price:{}},
	{"chnum":158, "chname":"J SPORTS 3 HD", chelement:{osu:[]},price:{}},
	{"chnum":159, "chname":"時代劇専門チャンネルHD", chelement:{option:[], osu:[]},price:700},
	{"chnum":160, "chname":"MONDO TV HD", chelement:{ent:[], ote:[]},price:{}},
	{"chnum":161, "chname":"ミュージック･エア", chelement:{option:[], dor:[]},price:600},
	{"chnum":162, "chname":"MUSIC ON! TV HD", chelement:{osu:[]},price:{}},
	{"chnum":163, "chname":"キッズステーションHD", chelement:{osu:[]},price:{}},
	{"chnum":164, "chname":"グリーンチャンネルHD", chelement:{option:["set"]},price:{set:1200}},
	{"chnum":165, "chname":"グリーンチャンネル2HD", chelement:{option:["set"]},price:{set:0}},
	{"chnum":166, "chname":"日テレジータスHD", chelement:{osu:[]},price:{}},
	{"chnum":167, "chname":"ゴルフネットワークHD", chelement:{osu:[]},price:{}},
	{"chnum":168, "chname":"J SPORTS 1 HD", chelement:{osu:[]},price:{}},
	{"chnum":169, "chname":"J SPORTS 2 HD", chelement:{osu:[]},price:{}},
	{"chnum":170, "chname":"ミュージック・ジャパンTV", chelement:{option:[]},price:400},
	{"chnum":171, "chname":"カートゥーンネットワークHD", chelement:{osu:[]},price:{}},
	{"chnum":172, "chname":"QVC", chelement:{},price:{}},
	{"chnum":173, "chname":"東映チャンネルHD", chelement:{option:[]},price:1500},
	{"chnum":174, "chname":"ＫＮＴＶ ＨＤ", chelement:{},price:{}},
	{"chnum":175, "chname":"歌謡ポップスチャンネルHD", chelement:{option:[], osu:[]},price:800},
	{"chnum":176, "chname":"TBSチャンネル2", chelement:{sup:[]},price:{}},
	{"chnum":177, "chname":"ジャパネットチャンネルDX", chelement:{},price:{}},
	{"chnum":178, "chname":"CNN/US HD", chelement:{option:[], ent:[]},price:1600},
	{"chnum":180, "chname":"CNNj ", chelement:{osu:[]},price:{}},
	{"chnum":181, "chname":"Mnet HD", chelement:{option:[]},price:2300},
	{"chnum":182, "chname":"AT-X HD!", chelement:{option:[]},price:1800},
	{"chnum":183, "chname":"ディズニー・チャンネルHD", chelement:{},price:{}},
	{"chnum":184, "chname":"KBS", chelement:{ent:[]},price:{}},
	{"chnum":185, "chname":"日経CNBC HD", chelement:{option:[], osu:[]},price:900},
	{"chnum":186, "chname":"アニマルチャンネル", chelement:{osu:[]},price:{}},
	{"chnum":187, "chname":"エンタメ～テレHD", chelement:{option:[], ent:[]},price:600},
	{"chnum":188, "chname":"テレ朝チャンネル2", chelement:{option:[], dor:[]},price:600},
	{"chnum":191, "chname":"パチンコ★パチスロTV! HD", chelement:{option:[]},price:1000},
	{"chnum":192, "chname":"ジュエリー☆GSTV", chelement:{},price:{}},
	{"chnum":195, "chname":"Ｖ☆パラダイスＨＤ", chelement:{option:[]},price:700},
	{"chnum":196, "chname":"囲碁・将棋チャンネルHD", chelement:{osu:[]},price:{}},
	{"chnum":252, "chname":"日テレNEWS24", chelement:{sup:[], ote:[]},price:{}},
	{"chnum":284, "chname":"日テレプラス", chelement:{sup:[]},price:{}},
	{"chnum":291, "chname":"レッドチェリー", chelement:{option:[]},price:2500},
	{"chnum":393, "chname":"レインボーチャンネルHD", chelement:{option:[]},price:2300},
	{"chnum":394, "chname":"プレイボーイ チャンネル HD", chelement:{option:[]},price:2500},
	{"chnum":400, "chname":"たうんch4K", chelement:{},price:{}},
	{"chnum":401, "chname":"ケーブル4K", chelement:{},price:{}},
	{"chnum":416, "chname":"ショップチャンネル4K", chelement:{},price:{}},
	{"chnum":417, "chname":"4K QVC", chelement:{},price:{}},
	{"chnum":418, "chname":"ザ・シネマ4K", chelement:{osu:[]},price:{}},
	
	
];

/*let list_example =[
	{chNum:111},
	{chName:"aaa"},
	{chElement:["osusume","dorama&ongaku","option"]},
	{price:1000}//optionあれば、なければnull
]
*/

const pack_list = {
	Osusume : {ch_list:[168,169,158,123,122,167,135,125,159,121,186,146,149,163,
		148,153,162,126,157,196,418,124,134,145,171,143,166,180,175,185,152,120,156,151],
		price:3200},	//+放送大学？
	Otegaru : [147,252,155,150,131,142,160],
	Doraon : [136,188,141,155,150,161],
	Supobara : [147,138,139,144,176,252,284],
	Entame : [131,142,160,187,105,178,184]
};